headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/stevegowa/Documents/GitHub/lendpaper"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/waterfall.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"